# Generated by Django 5.1.7 on 2025-05-07 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nr_sessions', models.IntegerField(default=0)),
                ('total_km', models.FloatField(default=0.0)),
                ('km_z3_4', models.FloatField(default=0.0)),
                ('km_z5_t1_t2', models.FloatField(default=0.0)),
                ('km_sprinting', models.FloatField(default=0.0)),
                ('strength_training', models.BooleanField(default=False)),
                ('hours_alternative', models.FloatField(default=0.0)),
                ('perceived_exertion', models.FloatField(default=-0.01)),
                ('perceived_training_success', models.FloatField(default=-0.01)),
                ('perceived_recovery', models.FloatField(default=-0.01)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
